### ISSUE TITLE
Investigate meal title linebreaking

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/MensaDresden#11]
![original](https://user-images.githubusercontent.com/2625584/66073876-43ddc180-e558-11e9-9bee-6bd884a60dec.jpg)

**Comment by pacocd** [comment]
hey, I can give you some help with this

**Comment by kiliankoe** [comment]
Hi @pacocd! That would be fantastic! Do you have any idea what might be causing this issue? The relevant view is here:

https://github.com/kiliankoe/MensaDresden/blob/e3fc042a8722b789d89bfc1e3cd698b454aef423/MensaDresden/MealList/MealDetailView.swift#L25-L28

It's especially weird since `.lineLimit(5)` should stop it from doing this, which seems to work for most cases, but unfortunately not all.

**Comment by pacocd** [comment]
yeah, I am taking a look on whole view, it may be related to layout priorities

**Comment by pacocd** [comment]
@kiliankoe I've been doing some research about this issue. Looks like an internal issue with SwiftUI. Some people says that it can be fixed changing `Text` wrappers, but it this case is not working.

**Comment by kiliankoe** [comment]
Yeah, I've heard similar reports. Thanks so much for looking into it though!

**Comment by pacocd** [comment]
Already found a solution, I'm preparing a PR with the fix 😄

**Comment by kiliankoe** [comment]
Thanks for fixing this with #23!

Happy Hacktoberfest 😊🎃
