### ISSUE TITLE
Rotation error on iPad

### ISSUE THREAD

**Issue by pixix4** [kiliankoe/MensaDresden#55]
There is a rotation bug in the detail view. When you view the details of a dish and rotate the device, the next screen is the list of all dishes and not the detail view.

**Comment by kiliankoe** [comment]
Probably related to #38.

**Comment by kiliankoe** [comment]
I can no longer reproduce this, I guess it was a SwiftUI issue and has been fixed on the betas. The navigation stack still behaves a bit awkward on iPad though, hoping to fix that soon.
