### ISSUE TITLE
Wrong format error

### ISSUE THREAD

**Issue by vallivh** [kiliankoe/MensaDresden#67]
In der App wird unter "Speiseplan" nichts angezeigt. Stattdessen erscheint nur die Fehlermeldung "Die Daten konnten nicht gelesen werden, da sie nicht das korrekte Format haben. Versuche es noch einmal." Beim Tippen darauf ändert sich nichts.

**Comment by kiliankoe** [comment]
Hi @vallivh!

Seit letztem Donnerstag wirft der Server vom Studentenwerk leider nur Server Errors. Sobald die Probleme dort beseitigt werden geht hoffentlich alles einfach wieder. Ist leider etwas doof 😕

**Comment by kiliankoe** [comment]
Sollte jetzt wieder laufen 🎉
