### ISSUE TITLE
How deos Emeal scanning work?

### ISSUE THREAD

**Issue by qmnl** [kiliankoe/MensaDresden#68]
This is just a question. If you don't have time to answer it, just close it :)

How does the Emeal NFC scanning work? Why do other raw NFC communication apps not show the card? Is it a special standard or does your app somehow communicate with the tag (seems like this in the source code)? Can you give me some pointers on where I can get further information?

**Comment by qmnl** [comment]
See #17

**Comment by kiliankoe** [comment]
Hi Simon,

I struggled with this a bit as well. The basic idea is that Emeals (like other MiFare cards) aren't like NFC NDEF tags in that they just store some data which can be read, but they run their own operating system (which sounds pretty fancy for a plastic card) that can respond to certain commands which are written onto the card by the reader.

There must be some documentation on how this works somewhere, but [my implementation](https://github.com/kiliankoe/MensaDresden/blob/master/MensaDresden/EmealView/Emeal.swift) is largely adapted from [schorschii/MensaGuthaben-iOS](https://github.com/schorschii/MensaGuthaben-iOS).

Sorry I can't be of too much help regarding any more information, but please feel free to share anything else you might come across here. I'd love to know more about this as well 😄

**Comment by kiliankoe** [comment]
I'm going to go ahead and close this as it's not really an issue per se, but feel free to keep the conversation going.

**Comment by qmnl** [comment]
Some links:

[0] https://de.wikipedia.org/wiki/Mifare
[1] https://en.wikipedia.org/wiki/ISO/IEC_14443
[2] https://developer.apple.com/documentation/corenfc/nfcmifaretag
[3] https://www.mifare.net/support/forum/topic/documentation-desfire-ev1/

The documentation for the MiFare cards seems to be restricted to their customers [3].
