### ISSUE TITLE
Menu screen does no longer load canteens

### ISSUE THREAD

**Issue by qmnl** [kiliankoe/MensaDresden#70]
Version 2019.5 Build 22

Since today the canteens are not loading anymore, even though other internet related services work:

[Screenshot](https://user-images.githubusercontent.com/16321843/70924285-2a112e00-2021-11ea-9b80-f35b60355ddb.jpeg)

**Comment by kiliankoe** [comment]
I have the same issue :/ The weird thing is that it still works on other devices...

**Comment by kiliankoe** [comment]
Found the culprit, I was doing something stupid that shouldn't have been working, but apparently did until Apple suddenly fixed the behavior in current iOS. I'm going to try and release an update right after Apple's holiday shutdown.

Thanks again for the issue!
