### ISSUE TITLE
Prices at Mensa Johannstadt don’t show up

### ISSUE THREAD

**Issue by jonasrichardrichter** [kiliankoe/MensaDresden#83]
Prices at Mensa Johannstadt don’t show up.

App Version: 2020.5(48)
iOS 14.1
iPhone 11

![533885EA-05B7-443F-9951-D7932F7E05B9](https://user-images.githubusercontent.com/33372485/98232170-9fe5f700-1f5d-11eb-8ede-79448be87253.png)

**Comment by kiliankoe** [comment]
Interesting, thank you for the issue! 
Looks like the Studentenwerk messed up their API response.

The relevant portion should look like this:
```js
"prices": {
  "Studierende": 2.55,
  "Bedienstete": 4.64
},
```

It however looks like this at Mensa Johannstadt (notice the extra colons):
```js
"prices": {
  "Studierende:": 2.35,
  "Bedienstete:": 4.27
},
```

I'll see if I can contact them about this 👍

**Comment by kiliankoe** [comment]
I just pushed a new build that also works around this. I'm pretty sure the system behind the server is pretty janky and *probably* depends on a lot of data being supplied by all of the canteens. I have no clue how that runs, but I really wouldn't be surprised if this is somehow based on a bunch of Excel files or something 😅 A colon probably makes sense on their side as a separator, so maybe it'll happen again 🤷‍♀️

**Comment by kiliankoe** [comment]
The update is now live and everything should work again. Thanks for reporting the issue!
