### ISSUE TITLE
iPad SplitView Layout issues

### ISSUE THREAD

**Issue by jonasrichardrichter** [kiliankoe/MensaDresden#89]
When using SplitView on the iPad. The Layout of the meal page is not usable.
![IMG_0218](https://user-images.githubusercontent.com/33372485/166245892-9b6af2cd-a75e-4985-ab2f-28f7ceac9679.png)
![IMG_0219](https://user-images.githubusercontent.com/33372485/166245910-81ee48f2-76c8-47d0-8ea1-d4fead4d0705.png)
![IMG_0220](https://user-images.githubusercontent.com/33372485/166245998-aa1e65c9-9faa-4cbf-a7ad-df2764900e5e.png)

**Comment by kiliankoe** [comment]
Oh, nice find! I always forget that that's a thing on iPad.

**Comment by kiliankoe** [comment]
I've abandoned the broken iPad specific layout in the most recent update. While not quite as pretty, it should be more functional now. In upcoming releases this'll likely become a bit better looking again on iPad.
